### ISSUE TITLE
Add support for animation events

### ISSUE THREAD

**Issue by sorvell** [web-animations/web-animations-js-legacy#131]
The spec supports a concept of TimingEvents (https://dvcs.w3.org/hg/FXTF/raw-file/default/web-anim/index.html#timing-events).

Will TimingEvents be supported in the polyfill?

To synchronize actions with animations, it's particularly important to support an end event. Perhaps this could be implemented ahead of full support for TimingEvents.

**Comment by birtles** [comment]
Yes, it's critical to support it. But I'd hold off for a few weeks since that part of the spec is probably going to be significantly revised.

As for why it's critical, it's for stuff like this:

elem.animate({ opacity: '0%' }, 2).onend =
  function(evt) { evt.target.parentNode.removeChild(evt.target); };

**Comment by theone1984** [comment]
I'd also like to see these callbacks.

**Comment by gavindoughtie** [comment]
Yes please. It's idiomatic in many frameworks.

**Comment by dstoc** [comment]
Events were implemented here: https://github.com/web-animations/web-animations-js/pull/287
